title: Trinidad Annual Report 2013

links:
  ar_pdf: http://www.trinidaddrilling.com/Reports/TDG-2013-AR.pdf
  fs_pdf: http://www.trinidaddrilling.com/Reports/TDG-2013-FS.pdf
  mda_pdf: http://www.trinidaddrilling.com/Reports/TDG-2013-MDA.pdf
  services: http://www.trinidaddrilling.com/Services
  contact: trinidad@trinidaddrilling.com

staticpath: ''

navigation:
  - title: The Steps
    url: "#/page/the-steps"
  - title: Letter to Shareholders
    url: "#/page/letter-to-shareholders"
  - title: Operations
    url: "#/page/operations"
  - title: "MD&A And Financials"
    url: "#/page/md-a"
  - title: Contact Us
    url: "#/page/contact-us"
