title: Trinidad Annual Report 2013

links:
  operations: http://www.trinidaddrilling.com/Services.aspx
  ar_pdf: http://www.trinidaddrilling.com
  mda_pdf: http://www.trinidaddrilling.com
  contact: trinidad@trinidaddrilling.com

staticpath: ''

navigation:
  - title: The Steps
    url: "#/page/the-steps"
  - title: Letter to Shareholders
    url: "#/page/letter-to-shareholders"
  - title: Operations
    url: "#/page/operations"
  - title: "MD&A And Financials"
    url: "#/page/md-a"
  - title: Contact Us
    url: "#/page/contact-us"
