title: Trinidad Annual Report 2013
links:
  operations: http://www.trinidaddrilling.com
  ar_pdf: http://www.trinidaddrilling.com
  mda_pdf: http://www.trinidaddrilling.com
  contact: trinidad@trinidaddrilling.com
